rsksmart/2wp-app

src/components/create/BtcTxSummarySide.vue
src/components/create/PegInAccountSelect.vue

I've added a column to the combo size in order to fit
the entire balance

Update account type combo

---

src/middleware/TxBuilder/TxBuilder.ts
src/services/ApiService.ts
src/services/WalletService.ts
src/store/peginTx/getters.ts
src/types/Common.ts
src/types/pegInTx.ts

I've changed the unusedAddress method response for the
apiService getting every single unused value of the
address list. also I update the changeAddress method and
startAskingForBalance in order to store the unused value
and retrieve without make more calls

Refactor unusedAddress

---

src/components/exchange/TxSummary.vue
src/views/Status.vue
tests/unit/TxSummary.spec.ts

I've updated the status view in order to ask for the btc
price on the component creation.

fixing btc price load

---

src/middleware/TxBuilder/TxBuilder.ts

I've updated the Txbuilder in order to check the
changeAddress anly if ther are change output present on
the normalized Tx

Updating handle no change output case

---

src/components/layouts/Top.vue

Fixes testnet logoc not being shown due to a typo and not being used

Fixes testnet logo not being shown

---

src/components/create/BtcTxSummarySide.vue
src/components/create/PegInAccountSelect.vue
src/types/SatoshiBig.ts
tests/unit/SatoshiBig.spec.ts

Fixes balance format.
Created new SatoshiBig:: toBTCStringNotZeroPadded method that  detects if the balance has the format '0.000...' and corrects it.
Add a unit test.

Fixes balance format

---

src/components/create/SendBitcoin.vue
src/components/ledger/ConfirmLedgerTransaction.vue
src/components/trezor/ConfirmTrezorTransaction.vue
src/middleware/TxBuilder/LedgerTxBuilder.ts
src/middleware/TxBuilder/TrezorTxBuilder.ts
src/middleware/TxBuilder/TxBuilder.ts

I've updated the Txbuilder class in order to remove
redundant data. Also making stateless the txbuilder
class.

Txbuilder refactors

---

src/components/exchange/ConnectDevice.vue
src/services/WalletService.ts

I've fixed the generated error avoiding to clear the
store once it was clear before by the form.

Fixing balance charge error

---

src/components/create/SendBitcoin.vue
src/components/liquality/ConfirmLiqualityTransaction.vue
src/middleware/TxBuilder/LiqualityTxBuilder.ts
src/utils/OpReturnUtils.ts
tests/unit/OpReturnUtils.spec.ts

I've created the ConfirmLiquality Component in order to
handle the last step of liquality pegin, also the
liquality opReturn without

Updating OpReturn verifications for outputs

---

.eslintrc.js
src/services/ApiService.ts
src/types/store.ts
src/views/Status.vue

Started using the new endpoint /tx-status to get the pegin and pegout statuses.
An initial refactor work was done in the Status.vuew file, but more refactor is necessary. Left a few TODO and I will create a few stories describing some of the refactors and changes needed.

Starts using new /tx-status endpoint

---

.env.local.test
package-lock.json
package.json
src/services/LedgerService.ts
src/services/LedgerTransportService.ts
src/services/TrezorService.ts
src/services/WalletService.ts
src/store/constants.ts
tests/utils/MockedWallet.ts

I've updated Wallet service with and abstract method tha
should be implemented for xpub value obtaining

Getting xpub value from ledger

---

README.md
tests/unit/txSummary.spec.ts

This PR adds more information in Unit Test section and fix an error message related to an unknown getter.

Update README and Unit Tests

---

ENV_VARIABLES.md
README.md

Adding Environment Varibles information

---

package-lock.json
package.json

I've forced the ledgerHQ packages version in order to
ensure @ledgerhq/devices/hid-framing were installed.

Force ledger version to 6.27.1

---

src/services/LiqualityService.ts
src/services/WalletService.ts
src/types/Liquality.ts
src/types/exception/LiqualityError.ts
tests/unit/services/LiqualityService.spec.ts
tests/utils/MockedBtcProvider.ts

Correcting these errors:
- Error when the user closes the Liquality popup
- Error when the user has no balance
- Error when the user selects the wrong network

Treat Liquality Errors

---

src/components/liquality/ConfirmLiqualityTransaction.vue
src/styles/_exchange.scss

formato amount
spacing into the confirm box

confirm box

---

.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml
.github/workflows/deploy_staging_TestNet_UI.yml
src/services/LedgerService.ts
src/services/LiqualityService.ts
src/services/TrezorService.ts
src/services/WalletService.ts

I've updated Wallet services in order to implement its
specific areEnoughUnusedAddress method based on the address
type each handle.

Fix address request for liquality

---

.github/workflows/build.yml

Change node version to recommended 16

change node version on build.yml

---

.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml
.github/workflows/deploy_staging_TestNet_UI.yml

**Updated**
- Testnet prod
- Mainet prod

update deployed URLs on workflows

---

src/services/ApiService.ts
src/services/WalletService.ts
src/services/utils.ts
src/types/pegInTx.ts

- request adjusted
removed unused parameters:
````
derivationPath: string;
arrayPath?: number[];
unused?: boolean;
publicKey: string;
````

removing unused objects on getBalance request

---

.github/workflows/build.yml

- remove the component failing

removing to add sonarcloud

---

.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml

- Deploy to mainnet ( push any tag with *-rc)
- Deploy to testnet ( push any branch with *-qa)

change deploy to mainnet and testnet

---

src/services/utils.ts
src/views/Status.vue

I've updated the status view in order to check and update the message when
a wrong txId input

fix status for pegout

---

src/components/create/PegInForm.vue
src/styles/_exchange-form.scss
src/styles/_exchange.scss

- Change the address color to black
- Change the Continue button to black
- Change the MyWallet component to black

Change UI -tx-screen-liquality- mywallet 

---

src/components/ledger/ConfirmLedgerTransaction.vue
src/components/liquality/ConfirmLiqualityTransaction.vue
src/components/trezor/ConfirmTrezorTransaction.vue

- Show correct fee value on resume transaction screen for:
- - Liquality
- - Ledger
- - Trezor

Correcting fee on resume tx screen

---

package-lock.json

- adding version 1.2.1 into the package-lock file.

updating version on package lock

---

package-lock.json
package.json

updating version to 1.2.2

---

src/middleware/TxBuilder/TxBuilder.ts
src/services/ApiService.ts
src/types/Common.ts
src/utils/OpReturnUtils.ts
src/utils/PowPegUtils.ts
tests/unit/OpReturnUtils.spec.ts
tests/unit/PowPegUtils.spec.ts
tests/unit/services/ApiService.spec.ts
tests/unit/txSummary.spec.ts

I've used the returned rawTx in order to check the input integrity, also comparing it with
the userAddressList

Add Inputs validation on the createPeginTx api endpoint

---

src/utils/OpReturnUtils.ts
tests/unit/OpReturnUtils.spec.ts

I've updated the op_returt output validation in order to check if the address field
are unset.

Update op_return validation

---

tests/unit/services/ApiService.spec.ts

I've added the unit test for utxos types

Add unit test for segwit, native segwit and legacy utxos

---

src/components/exchange/TxSummaryFixed.vue
src/components/layouts/Footer.vue
src/components/pegout/Confirmation.vue
src/components/pegout/RbtcInputAmount.vue
src/styles/_exchange-form.scss
src/styles/_status.scss

- Copyright message adjusted
- terms and conditions link adjusted
- Pegout confirmation page message changed to : “Your BTC is on its way!” 
- Pegin tx summary Label changed to TRBTC destination address:
- Changed the Max Button to bellow the textbox and the title was changed to : Use max available balance”

Adjusting front-end

---

package-lock.json
package.json
src/store/session/actions.ts

I've included the ledger and trezor provider for Rlogin
in order to use then in the pegin and pegout proccess

Attmpting to include hw wallets

---

src/store/constants.ts

Updated url to link the new documentation in dev portal.

Update documentation url

---

src/components/pegout/Confirmation.vue
src/store/constants.ts
src/styles/_transactions.scss
src/views/PegOut.vue

Added a message at the end of the peg-out creation process with a link to the documentation informing how to get the funds in BTC.

Add message on final peg-out tx screen

---

src/styles/_status.scss

- correct the styled status bar in the search screen

correcting the styled bar

---

src/styles/_status.scss

fix styled bar and run pipeline

---

package-lock.json
package.json
src/common/components/exchange/DeviceErrorDialog.vue
src/common/services/ApiService.ts
tests/setup.js
tests/unit/components/AddressWarningDialog.spec.ts
tests/unit/components/AdvancedData.spec.ts
tests/unit/components/DeviceErrorDialog.spec.ts
tests/unit/services/ApiService.spec.ts
tests/unit/views/Create.spec.ts
tests/unit/views/PegIn.spec.ts
tests/unit/views/PegOut.spec.ts

Added some unit tests of components and services.
```
=============================== Coverage summary ===============================
Statements   : 30.05% ( 683/2273 )
Branches     : 32.25% ( 198/614 )
Functions    : 26.48% ( 125/472 )
Lines        : 30.25% ( 674/2228 )
================================================================================
```
```
=============================== Coverage summary ===============================
Statements   : 51.78% ( 1177/2273 )
Branches     : 34.69% ( 213/614 )
Functions    : 33.47% ( 158/472 )
Lines        : 51.75% ( 1153/2228 )
================================================================================
```

Increase unit tests

---

src/common/components/exchange/TxSummaryFixed.vue

Change "Not found" value to "-" value

Change sender address value when wallet is not connected yet

---

src/common/components/exchange/TxSummaryFixed.vue
src/pegout/components/PegOutForm.vue
src/pegout/components/RbtcInputAmount.vue
src/pegout/components/RskWalletConnection.vue

Revert "Feature/handle vuetour overlapping"

---

src/common/components/exchange/TxSummaryFixed.vue
src/common/styles/_exchange.scss
src/pegin/components/create/BtcFeeSelect.vue
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/RskAddressInput.vue

Revert "Feature/introjs pegin"

---

src/common/styles/_exchange.scss
src/pegout/components/PegOutForm.vue

Revert "Customize vue-tour for pegout"

---

.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml
.github/workflows/deploy_staging_TestNet_UI.yml
ENV_VARIABLES.md

- remove unused variables
- adjust the correct value of all variables

adjusting value of maxaddress per call

---

src/common/components/exchange/TxSummary.vue
src/common/components/status/TxPegin.vue
src/common/types/store.ts
src/common/utils/utils.ts
src/pegout/components/RbtcInputAmount.vue

Fix the error when the just made pegin or pegout is not visible correct in the tx status screen

fix: correct pending pegout status

---

src/common/utils/utils.ts
src/pegout/store/pegoutTx/actions.ts
src/status/store/status/actions.ts
tests/unit/utils/utils.spec.ts

- change in tx status
- change in pegout tx screen
- added a simple function in utils.js

adding new calculation formula to estimated fee

---

src/common/components/exchange/TxSummaryFixed.vue
src/common/styles/_exchange-form.scss
src/common/styles/_site.scss
src/pegin/components/create/BtcFeeSelect.vue
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/SendBitcoin.vue
src/pegout/components/PegOutForm.vue
src/pegout/components/RbtcInputAmount.vue
src/pegout/components/RskWalletConnection.vue
src/pegout/views/PegOut.vue

Adjusted sizes between peg-in and peg-out screens.

Fix layout spacing

---

README.md
package.json

Created `npm run test` command to execute tests like in API.

Add test command

---

src/App.vue

Including hotjar script in the CSP

Change content security policy

---

src/common/components/exchange/TxSummaryFixed.vue
src/common/styles/_exchange-form.scss
src/common/styles/_status.scss

- Fixed white gap between bar and circles in pegin search
- Deleted padding-bottom that makes operation summary fields to be misaligned

Fix minor style issues

---

src/common/components/exchange/TxSummaryFixed.vue

- Changes recipient field title
- Shows longer string on address fields

Equalize summary

---

src/common/styles/_exchange-form.scss
src/pegin/components/create/BtcFeeSelect.vue
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInAccountSelect.vue
src/pegin/components/create/RskAddressInput.vue
src/pegout/components/PegOutForm.vue
src/pegout/components/RbtcInputAmount.vue
src/pegout/components/RskWalletConnection.vue

- Use same button style
- Add wallet connected label
- Align sections
- Change fast fee option color to green
- Equalize section where is introduced the amount to convert

Equalize pegin and pegout screens

---

src/common/components/layouts/Footer.vue

- Added support item
- Changed help link

Change footer

---

src/common/providers/EnvironmentContextImplMainnet.ts
src/common/providers/EnvironmentContextImplTestnet.ts
src/common/store/constants.ts
src/common/utils/utils.ts

- fix code duplication
- tests running fine: npm run test:unit -t  tests/unit/utils/utils.spec.ts

fix code duplication

---

.env.local.test
.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
ENV_VARIABLES.md
src/App.vue
src/common/components/exchange/TxSummaryFixed.vue
src/common/types/environment-variables.ts
src/main.ts
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInForm.vue
src/pegin/store/peginTx/actions.ts
src/pegout/components/PegOutForm.vue
src/pegout/components/RbtcInputAmount.vue

- added max button on pegin 
- added clarity tag to have analytics of user navigation 
- fixed tour bug

implementing max button

---

.env.local.test
.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
ENV_VARIABLES.md
src/App.vue
src/common/types/environment-variables.ts
src/main.ts

- adding hot jar implementation

hot jar implementation

---

src/pegin/components/create/PegInForm.vue
src/pegout/components/PegOutForm.vue

hiding tourjs from 1.5.0 version

---

src/App.vue
src/pegin/components/create/PegInForm.vue
src/pegout/components/PegOutForm.vue

fix safe url connection

---

.env.local.test
.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
ENV_VARIABLES.md
src/App.vue
src/common/types/environment-variables.ts
src/main.ts
src/pegin/components/create/PegInForm.vue
src/pegout/components/PegOutForm.vue

- applying release candidate to main branch

Release candidate

---

src/common/components/exchange/TxSummaryFixed.vue
src/common/styles/_exchange-form.scss

- adding fiat amount in pegout form

adding pegout fiat amounts

---

src/pegout/components/AddressDialog.vue
src/pegout/components/PegOutForm.vue

Derivated address -> destination address
Derive -> get

Replace derivation-related words

---

.github/workflows/deploy_staging_TestNet_UI.yml

- test the deploy in staging-testnet environment

configuring staging testnet deploy

---

src/common/components/layouts/Footer.vue

- Will not working for version 1.5.0 because the release was wrong name (v-1.5.0) the correct one needs to be v1.5.0

Change the link of the version

---

src/common/store/session/actions.ts
src/main.ts

Change how we access web3 instance

Fix get balance error

---

package.json
src/common/styles/_exchange-form.scss
src/pegin/components/create/PegInAccountSelect.vue

Fix peg-in screen account selection combo.

Fix account selection

---

.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml

- changed for testnet to test, and this configuration is working fine
> this PR changes:
- **staging-mainnet** configuration 
- **testnet** configuration
- **mainnet** configuration

ci cd change node version

---

.github/workflows/deploy_staging_TestNet_UI.yml

- change the trigger to deploy in staging-testnet to branch qa

changing the trigger for staging-testnet to qa branch

---

.github/workflows/build.yml
sonar-project.properties

Define scope of analysis for test and non-test code.
Exclude files from coverage to match Jest report.

Update sonar config

---

package-lock.json

- Bump electron from 24.8.1 to 24.8.5.
- Bump @babel/traverse from 7.22.11 to 7.23.2

Resolve dependabot alerts

---

src/App.vue
src/common/types/environment-variables.ts
src/main.ts
src/pegin/components/ledger/ConfirmLedgerTransaction.vue
src/pegin/components/liquality/ConfirmLiqualityTransaction.vue
src/pegin/components/trezor/ConfirmTrezorTransaction.vue
src/pegout/components/Confirmation.vue

- testing hotjar working with clarity
- testing new tags

adding hot jar

---

src/common/components/status/TxPegin.vue

Fix status bar style for confirmed pegin

---

package-lock.json
package.json
src/common/components/layouts/Footer.vue

Replace slack with discord to support users.

Add discord link

---

src/common/store/constants.ts
src/pegin/services/TxFeeService.ts
tests/unit/pegin/services/TxFeeService.spec.ts

https://github.com/rsksmart/2wp-api/blob/release-candidate/src/controllers/tx-fee.controller.ts#L73

Add missing number of outputs to fee calc

---

src/pegin/components/create/SendBitcoin.vue
src/pegin/store/getters.ts

We've updated the change address getter on the peginTx module
checking the derivation path structure of liquality.

Fix change address getter

---

src/common/components/status/TxPegin.vue

removing unused watch

---

src/common/services/ApiService.ts
src/common/types/environment-variables.ts
src/pegin/services/TxFeeService.ts
tests/unit/pegin/services/TxFeeService.spec.ts

We've updated the ApiService to return the fee rate in Btc per byte

fix tx fee calculation

---

src/common/components/exchange/TxSummaryFixed.vue
src/common/store/constants.ts
src/common/styles/_status.scss
src/pegout/components/Confirmation.vue
src/pegout/components/PegOutForm.vue
src/status/views/Status.vue

Add a link to the derivation docs in the transaction summary when a peg-out is finished.

Add link to derivation docs

---

.gitignore
package-lock.json
package.json
src/App.vue
src/common/services/FlyoverService.ts
src/common/services/index.ts
src/common/types/Flyover.ts
src/common/types/WeiBig.ts
src/common/types/index.ts
src/pegout/store/pegoutTx/actions.ts

I've defined the FlyoverService usign with flyover sdk and using the getProviders
function to list the providers available

Add Flyover service

---

.github/workflows/build.yml
.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml
.github/workflows/deploy_staging_TestNet_UI.yml

We'll need to create a github classic token with read access to registries and add it as NPM_TOKEN secret

feat(): .github/workflows/: add npmrc configuration for build process

---

src/pegout/components/BtcRecipientInput.vue
src/pegout/components/FlyoverPegout.vue
src/pegout/components/FlyoverRbtcInputAmount.vue
src/pegout/components/RskWalletConnection.vue

Adjust peg-out screen

---

src/pegin/components/create/RskAddressInput.vue
src/status/views/Status.vue

- changing the message when the user is using an incompatible address according to ERC=1191

Changing the warning message

---

src/common/utils/utils.ts
src/pegout/components/FlyoverPegout.vue
src/pegout/components/PegoutOption.vue
src/pegout/store/FlyoverPegout/actions.ts

Show default option if flyover fails

Show default option

---

package-lock.json
package.json
src/common/components/exchange/TxSummaryFixed.vue
src/common/types/Common.ts
src/pegout/components/Confirmation.vue
src/pegout/components/FlyoverPegout.vue
src/pegout/components/PegOutForm.vue
src/pegout/components/RbtcInputAmount.vue
src/pegout/views/SuccessPegout.vue

I've updated the flyover.pegout implementation based on the vulnerabilities
the security team found.
- Stacks library removed
- Fixed `.env.test` file data
- Use Big types instead of Number for Rbtc and Btc amounts except for front display

Fix security vulnerabilities

---

src/common/router/index.ts
src/common/views/SuccessTx.vue
src/pegin/components/create/SendBitcoin.vue
src/pegout/components/PegOutForm.vue

[TWPAPP-691](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-691)
| | |
|:-------------------------:|:-------------------------:|
| <img width="350" alt="Screenshot 2024-05-14 at 9 41 21 AM" src="https://github.com/rsksmart/2wp-app/assets/7018960/bd1f4442-27dc-46b3-8962-c6410e36c427">| <img width="350" alt="Screenshot 2024-05-14 at 9 41 28 AM" src="https://github.com/rsksmart/2wp-app/assets/7018960/1f2c246f-eb44-4bd0-9876-91a1ccc2ccfb">| 
| <img width="350" alt="Screenshot 2024-05-09 at 7 08 16 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/0a69f13a-76fd-4456-912a-3507ba72d71e">| <img width="350" alt="Screenshot 2024-05-09 at 7 08 21 PM" src="https://github.com/rsksmart/2wp-app/assets/7018960/e4f87f1c-445d-4798-a961-8f176c5788de">|

refactor: tx completed redesing

---

src/App.vue
src/common/components/common/WarningDialog.vue
src/common/components/exchange/AddressWarningDialog.vue
src/common/components/layouts/Footer.vue
src/common/plugins/vuetify.ts
src/common/styles/inputs.scss
src/common/styles/main.scss
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInAccountSelect.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue
src/pegin/components/create/SendBitcoin.vue
src/scss/settings.scss

Redesign pegin create page

---

src/common/components/layouts/Top.vue
src/common/utils/utils.ts
src/pegin/components/create/ConfirmTx.vue
src/pegin/components/create/ConfirmationSummary.vue
src/pegin/components/create/PegInAccountSelect.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue

Add pegin confirmation summary

---

src/common/plugins/vuetify.ts
src/pegin/components/create/BtcFeeSelect.vue
src/pegin/components/create/BtcInputAmount.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue
src/pegin/components/create/RskAddressInput.vue

I've added the input amount rules and the select address combo-box, also the selection
fee component

features pegin

---

src/App.vue
src/common/views/Home.vue

Change tc position

---

src/common/components/status/StatusProgressBar.vue
src/common/components/status/TxPegin.vue
src/common/components/status/TxPegout.vue

[TWPAPP-707](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-707)

refactor: status page search

---

src/common/components/status/StatusSummary.vue
src/common/components/status/TxPegin.vue
src/common/components/status/TxPegout.vue
src/common/types/Common.ts
src/common/types/store.ts
src/common/utils/utils.ts

Missing values:
- Sender address (pegin)
- Rootstock tx id (pegin)
- Gas fee (pegout)
- Bitcoin tx id (pegout)

Add status summary

---

src/common/components/status/StatusProgressBar.vue

[TWPAPP-742](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-742)
**Pegout status:**
**Flyover:**

refactor: pegout status

---

src/assets/status/ellipse_empty.svg
src/assets/status/ellipse_error.svg
src/common/components/status/StatusProgressBar.vue
src/status/views/Status.vue

[TWPAPP-744](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-744)

refactor: status bar for errors

---

src/common/components/layouts/Top.vue
src/common/store/session/actions.ts

Add full balace on hover

---

src/App.vue
src/common/views/Mobile.vue

[TWPAPP-684](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-684)

refactor: text on mobile

---

src/status/store/getters.ts

[TWPAPP-748](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-748)

fix: if time is negative show message

---

src/common/components/layouts/Footer.vue
src/common/components/layouts/Top.vue
src/common/providers/EnvironmentContextImplMainnet.ts
src/common/providers/EnvironmentContextImplTestnet.ts
src/common/providers/types.ts
src/common/utils/utils.ts
src/common/views/Home.vue
src/pegin/components/create/PeginOptionCard.vue
src/pegout/components/FlyoverPegout.vue
src/pegout/components/PegoutOption.vue

[TWPAPP-751](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-751)

refactor: text on pegout and pegin options, title on home

---

src/common/styles/_home.scss
src/common/styles/main.scss
src/common/views/Home.vue

[TWPAPP-758](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-758)

refactor: home buttons

---

src/pegout/components/FlyoverPegout.vue

[TWPAPP-843](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-843)

refactor: send pegout label

---

package-lock.json
package.json
src/App.vue
src/common/store/constants.ts
src/pegin/store/PeginTx/getters.ts

[TWPAPP-814](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-814)

fix: pegin leather refund

---

src/common/components/common/TermsContent.vue
src/common/store/constants.ts
src/common/store/session/actions.ts
src/common/views/Home.vue

[TWPAPP-842](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-842)

fix: terms and conditions

---

package-lock.json
package.json
src/common/services/LeatherService.ts
src/rsk-utils.d.ts
src/shims-tsx.d.ts

[TWPAPP-832](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-832)

fix: leather warning

---

src/common/components/common/PolicyDialog.vue
src/common/components/layouts/Footer.vue
src/common/services/FlyoverService.ts
src/common/utils/PowPegUtils.ts
src/common/views/Home.vue

- Private Policy content added
- all styles are used only to display this content based on the document received from legal, that's why the CSS content in inline internally on the file.

adding policy dialog

---

vue.config.js

Fix dev server config

---

package-lock.json

browserslist install

---

src/common/styles/_utilities.scss
src/common/styles/main.scss
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue
src/pegin/components/create/RskAddressInput.vue
src/pegout/components/FlyoverPegout.vue

Updates destination address combobox and pegout confirmation loader

Use connected wallet by default

---

src/common/components/status/StatusSummary.vue

[TWPAPP-869](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-869)

feat: add copy to clipboard option to summary fields

---

package-lock.json
package.json

updating version

---

src/common/views/Home.vue

[TWPAPP-880](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-880)

refactor: change T&C position

---

src/common/components/status/StatusSummary.vue

[TWPAPP-873](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-873)

refactor: copy disabled on summary

---

src/common/components/status/StatusSummary.vue
src/common/components/status/TxPegin.vue
src/common/components/status/TxPegout.vue
src/pegin/components/create/ConfirmTx.vue
src/pegin/components/create/ConfirmationSteps.vue

[TWPAPP-888](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-888)

refactor: fee specification for flyover and fix on steps component

---

src/common/plugins/vuetify.ts
src/common/styles/_cards.scss

[TWPAPP-872](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-872)

refactor: light mode option card colors

---

src/status/views/Status.vue

[TWPAPP-876](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-876)

fix: prevent api call for invalid txIds status

---

src/common/components/status/TxPegin.vue
src/status/views/Status.vue

[TWPAPP-892](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-892)

refactor: pegout native estimated time, pegin native confirmations

---

src/common/components/exchange/DeviceErrorDialog.vue
src/common/services/LeatherService.ts

I've forced the user session sign out in the service constructor
in order to make sure the connection is properly set. The previous
behavior manteined a previous user session started even if there was
disabled or disconnected Leather.

Fixing connection error on Leather wallet

---

src/pegin/components/create/PegInAccountSelect.vue

[TWPAPP-903](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-903)

refactor: updating Account type label

---

src/pegin/components/create/PeginOptionCard.vue
src/pegout/components/PegoutOption.vue

[TWPAPP-902](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-902)

refactor: updating pegin and pegout option card titles

---

src/common/components/status/StatusSummary.vue

[TWPAPP-915](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-915)

fix: flyover pegout summary order

---

package-lock.json
package.json
src/common/services/FlyoverService.ts
src/common/types/SatoshiBig.ts
src/pegin/components/create/ConfirmTx.vue
src/pegin/components/create/ConfirmationSteps.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue
tests/unit/SatoshiBig.spec.ts

- fix rounding mode
- fix labels with total amount
- update version to 2.2.1

Fixing Rounding Mode

---

jest.config.js
package-lock.json
package.json
src/common/services/FlyoverService.ts
tests/unit/common/services/FlyoverService.spec.ts

Dependabot:
[PR#827](https://github.com/rsksmart/2wp-app/pull/827)
[PR#822](https://github.com/rsksmart/2wp-app/pull/822)
[PR#821](https://github.com/rsksmart/2wp-app/pull/821)
[PR#808](https://github.com/rsksmart/2wp-app/pull/808)
[PR#806](https://github.com/rsksmart/2wp-app/pull/806)

refactor: dependabot suggestion

---

src/pegin/store/PeginTx/getters.ts

- Fix flyover option for xverse and enkrypt
- Adding refund address

fix: flyover xverse enkrypt

---

src/common/services/ApiService.ts
src/common/store/constants.ts
src/common/types/Common.ts
src/pegin/store/FlyoverPegin/actions.ts
src/pegout/store/FlyoverPegout/actions.ts

[TWPAPP-833](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-833)

feat: add api call to save logs for flyover getQuote and getLPS

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/deploy_MainNet_UI.yml
.github/workflows/deploy_TestNet_UI.yml
.github/workflows/deploy_staging_MainNet_UI.yml
.github/workflows/deploy_staging_TestNet_UI.yml
.github/workflows/scorecard.yml
LICENSE
README.md

[TWPAPP-963](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-963)
[OpenSSF Scorecard](https://www.notion.so/iovlabs/OpenSSF-Scorecard-0b0439593cc140fa97514bbe203a3e8e)

feature: open ssf scorecard

---

src/common/components/exchange/SelectBitcoinWallet.vue
src/common/styles/_buttons.scss

[TWPAPP-959](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-959)

fix: wallet position to the left and to fixed squares

---

src/common/components/status/StatusProgressBar.vue
src/common/components/status/TxPegin.vue
src/status/views/Status.vue

[TWPAPP-985](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-985)

fix: status bar bullets color of light mode

---

src/pegout/components/PegoutOption.vue

[TWPAPP-1009](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1009)

refactor: change generate to derive on pegput native button for BTC addr

---

src/pegout/store/FlyoverPegout/actions.ts

Fix provider definition on the flyoverservice instance on pegout

Provider fix pegout

---

src/pegout/components/PegoutOption.vue

[TWPAPP-1028](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1028)

fix: allow copy of the derived address pegout native

---

src/common/services/LeatherService.ts

[TWPAPP-1035](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1035)

fix: leather failing for fee verification

---

src/App.vue
src/status/store/actions.ts

[TWPAPP-1041](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1041)

refactor: enabling systema lps

---

package-lock.json

setting axios to v1.7.7

---

src/common/components/status/StatusProgressBar.vue
src/common/components/status/StatusSummary.vue
src/common/components/status/TxPegin.vue
src/common/components/status/TxPegout.vue
src/common/services/FlyoverService.ts
src/common/types/store.ts
src/status/views/Status.vue

Add txid to summary for flyover txs

---

src/common/components/status/StatusProgressBar.vue
src/status/views/Status.vue

Getting bitcoin usd from session, to avoid 0 usd values

Fix: usd status price

---

src/pegin/components/create/BtcInput.vue
src/pegin/components/create/PegInForm.vue
src/pegin/components/create/PeginOptionCard.vue

Fixing fee display on form pegin option

---

src/pegin/components/create/RskDestinationAddress.vue

[TWPAPP-1142](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1142)

feature: change invalid checksummed address to valid one

---

public/index.html

adding base path

---

src/common/components/exchange/SendQr.vue
src/common/router/index.ts
src/common/services/FlyoverService.ts
src/common/store/constants.ts
src/common/views/QrView.vue
src/pegin/components/create/PegInForm.vue
src/pegout/components/PegoutForm.vue

[TWPAPP-1161](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1161)

fix: qr code network names

---

src/common/types/store.ts
src/status/views/Status.vue

Include timer to search for a status loaded periodically until is completed

Status Timer
