rsksmart/2wp-app

src/services/WalletService.ts
I've fixed the behavior informing the subscribers if the
addresess are unused or with 0 balance. It allows to
display the form.
=> Fixing loading issue on empty wallets

src/middleware/TxBuilder/LiqualityTxBuilder.ts
I've updated Liquality tx builder using the input index
of the created transaction to be signed instead of the
utxo index
=> Fix index assignement liquality

src/components/exchange/DeviceErrorDialog.vue
Retry button is removed if wallet is liquality
Label changed to close if wallet is not liquality
=> button retry removed if wallet is Liquality and label changed to close

src/views/Status.vue
We've updated the status view in order to prevent the double call when
the url listener is called.
=> Double call fix

.github/workflows/build.yml, package.json
Changed the `test:unit` script to generate the cobertura.xml file
Added **_irongut/CodeCoverageSummary@v1.3.0_** to read the cobertura.xml report and validate the thresholds, in this case 30%.
Added **_marocchino/sticky-pull-request-comment@v2_** to create a comment on PR to show the coverage report.
=> Adding test coverage reporter

src/components/pegout/PegOutForm.vue, src/store/constants.ts, src/styles/_exchange-form.scss
Added a warning when the selected wallet is Liquality.
The "Get Bitcoin destination address" button remains disabled and a warning message appears with a link attached to redirect the user to the rsk documentation page.
=> warning message added when liquality wallet is used

src/components/exchange/TxSummaryField.vue, src/components/exchange/TxSummaryFixed.vue
New functionality to copy values from some of the transaction summary fields (sender address, recipient address, powpeg address and transaction hash) on double click and display a 'copied' message.
Created a separate component to properly handle the message tooltip. Based on the id, from the parent component the full value can be saved to the clipboard.
=> Copy values on double click

src/components/exchange/TxSummaryFixed.vue, src/styles/_exchange-form.scss
A link to RSK documentation for address derivation was added in recipient tooltip.
The cursor has also been modified to be a hand pointer only when it performs an action. 
https://github.com/rsksmart/2wp-app/assets/83707069/1fe52fba-44ef-4133-a8dd-0b30b7d6f733
Otherwise, the default one remains.
https://github.com/rsksmart/2wp-app/assets/83707069/00e25ba6-7425-468a-9176-8d5a3f151a3d
(This was also added to the tx-hash's mdi-information icon)
It all looks fine on final pegout stage page and on tx-status page.
=> Improve recipient tooltip

src/components/exchange/TxSummaryFixed.vue, src/styles/_site.scss, tests/unit/components/txSummary.spec.ts
On pegout transaction screen:
- Changed 'Transaction summary' to 'Operation summary' 
- Fixed spacing
- Removed all ':'
- Added divider
- Removed fields background
- Changed subtitles according to proposed design
=> Change pegout summary styles

src/pegin/services/UnusedAddressesService.ts, src/pegin/types/index.ts, tests/unit/pegin/services/UnusedAddressesService.spec.ts
Created unused addresses service to migrate that peg-in functionality from backend
=> Migrate unused addresses logic

src/pegin/views/Success.vue
Added an operation summary to standardize the pegin final screen with the pegout one.
=> Add operation summary to pegin success view

src/pegin/services/index.ts
We've created the TxFeeService in order to properly calculate the btc tx fee
based on the current utxo list provided. It adds some environment variables specifying
the min speed fee and the mining speed block.
=> Add Tx fee calculation

src/common/components/exchange/TxSummary.vue, src/common/types/session.ts, src/pegout/components/PegOutForm.vue
- Enable Derive button only if the provider is Meta mask
- Dont enable derived button if the user is using hw and mm plugin is enabled in the browser
=> fix derive button enabled

src/pegin/components/liquality/ConfirmLiqualityTransaction.vue
Increases pegin confirmation box width to avoid destination address using 2 lines.
=> Increase pegin confirmation box width

src/common/store/constants.ts, src/common/store/session/actions.ts, src/common/views/Home.vue, src/pegin/store/actions.ts, src/pegin/views/PegIn.vue, src/pegout/store/pegoutTx/actions.ts
Add a 0 default value if Coingecko promise is rejected and no Bitcoin price is set.
=> Handle missing BTC price

src/common/components/exchange/TxSummaryFixed.vue, src/pegin/components/create/BtcFeeSelect.vue
Fix pegin fee selection slider.
Add fiat value in USD for pegin summary fields: amount, fee and total.
=> Add fiat amounts to pegin summary

src/common/utils/utils.ts, src/pegout/store/pegoutTx/actions.ts, src/status/store/actions.ts
This PR solves the security comment above:
Vadym Kolisnichenko commented:
Hey [Alex Simas Braz](https://rsklabs.atlassian.net/secure/ViewProfile.jspa?accountId=623cd85a9b54ec0068b1bee2) ,
qq: do you know what was the reason to replace const estimatedFee = await getEstimatedFee(); with this calculation onst estimatedFee = pegoutQueueCount > 0 ? nextPegoutCost / pegoutQueueCount : 0; in actions.ts https://github.com/rsksmart/2wp-app/commit/22528d05d59649210ac835e4cdaa9bbab315538b#diff-677ba70779b5e66e7a47e4c6e9409baf147aa156a4bb85ad860a7dd152b26003L33
=> fixing to reuse the available function

src/common/services/ApiService.ts, src/pegin/components/ledger/ConfirmLedgerTransaction.vue, src/pegin/components/liquality/ConfirmLiqualityTransaction.vue, src/pegin/components/trezor/ConfirmTrezorTransaction.vue, src/pegout/components/PegOutForm.vue
Add session id required to register a transaction using the register endpoint (https://github.com/rsksmart/2wp-api/pull/263).
Send an empty string for pegouts until we modify sessions handling.
=> Send sessionId registering a tx

src/common/services/ApiService.ts, src/pegin/components/ledger/ConfirmLedgerTransaction.vue, src/pegin/components/liquality/ConfirmLiqualityTransaction.vue, src/pegin/components/trezor/ConfirmTrezorTransaction.vue
Uses the account balance text to get an user-friendly string and don't have to tailor constants only for this case.
=> Register address type

src/App.vue, src/common/components/common/TermsDialog.vue, src/common/components/layouts/Footer.vue, src/common/views/Home.vue
If Terms and Conditions are enabled
- Open the modal from the footer link
- Enable the back button if the text is not large enough to scroll
- Enable closing modal if terms are accepted by pressing esc or clicking outside the modal
=> Access T&C from footer

src/common/styles/_exchange-form.scss, src/pegout/components/PegOutForm.vue
I've updated the PegoutForm in order to chack the amount to receive
and do an explicit warning if the total fee to pay causes the received amount
to be zero or a negative value
=> Avoid negative amount to receive on pegout

src/App.vue, src/common/store/constants.ts, src/common/store/session/actions.ts, src/common/store/session/mutations.ts, src/common/utils/utils.ts, src/common/views/Home.vue, src/pegin/store/actions.ts, src/pegout/store/pegoutTx/actions.ts
I've added two functions to add and read the btc price on every module.
The cookie is fetched every time the btc price wants to be consulted, also
it has a default 12 hours expiration time
=> Add btc price cookie

src/pegin/components/create/RskAddressInput.vue
- fix the problem in the pegin page when the user is using a different checksum address
=> fixing checksum for non RSK address on pegin page

src/common/services/XverseService.ts, src/pegin/middleware/TxBuilder/XverseTxBuilder.ts
I've updated the signingInput collection on the xverse service in order to select
the inputs indexes of the created tx instead of the utxo.
Reported by <lucio.serra@iovlabs.org>
=> Fix signing inputs collection on xverse

package-lock.json, package.json
Bumps [protobufjs](https://github.com/protobufjs/protobuf.js) to 7.2.6 and updates ancestor dependency [@trezor/connect-web](https://github.com/trezor/trezor-suite). These dependencies need to be updated together.
Updates `protobufjs` from 7.2.4 to 7.2.6
- [Release notes](https://github.com/protobufjs/protobuf.js/releases)
- [Changelog](https://github.com/protobufjs/protobuf.js/blob/master/CHANGELOG.md)
- [Commits](https://github.com/protobufjs/protobuf.js/compare/protobufjs-v7.2.4...protobufjs-v7.2.6)
Updates `@trezor/connect-web` from 9.1.4 to 9.2.2
- [Release notes](https://github.com/trezor/trezor-suite/releases)
- [Changelog](https://github.com/trezor/trezor-suite/blob/develop/CHANGELOG.md)
- [Commits](https://github.com/trezor/trezor-suite/commits)
---
updated-dependencies:
- …
=> Bump protobufjs and @trezor/connect-web

src/assets/status/ellipse_empty.svg, src/common/components/status/StatusProgressBar.vue, src/common/components/status/StatusSummary.vue, src/common/components/status/TxPegin.vue, src/common/components/status/TxPegout.vue, src/common/types/Common.ts, src/status/views/Status.vue
[TWPAPP-756](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-756)
=> refactor: status bar gradient

src/common/store/constants.ts, src/common/store/session/actions.ts
I set the features data to be stored in a 48 hours cookie in order to reduce the
api calls
=> Add features to cookie storage

.env.local.test, .github/workflows/deploy_MainNet_UI.yml, .github/workflows/deploy_TestNet_UI.yml, .github/workflows/deploy_staging_MainNet_UI.yml, .github/workflows/deploy_staging_TestNet_UI.yml, ENV_VARIABLES.md, src/common/types/SatoshiBig.ts, src/main.ts, src/pegin/components/create/BtcInputAmount.vue
[TWPAPP-755](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-755)
=> refactor: updating max pegout to 10

src/common/components/status/StatusSummary.vue, src/common/styles/_inputs.scss, src/common/utils/utils.ts, src/pegin/components/create/ConfirmationSteps.vue
=> Fixing Confirmation page observations

src/common/utils/rlogin.ts
[TWPAPP-897](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-897)
Trezor connection for rsk address, fixed issue of not being able to connect when reloading the page for the cached provider of rLogin.
=> fix: remove cached provider from rLogin

src/pegin/components/create/PegInForm.vue, src/pegin/components/create/RskAddressInput.vue
[TWPAPP-875](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-875)
Prevent full size of pow peg option when flyover is not enabled
=> Fix: pegin option size

src/common/components/layouts/Top.vue
Prevents incorrect display of balances for low values expressed in exponential notation
=> Fix top balance format

src/common/services/FlyoverService.ts, src/common/types/Flyover/Flyover.ts, src/common/types/Flyover/FlyoverPegin.ts, src/common/types/Flyover/FlyoverPegout.ts, src/common/types/Flyover/PeginQuote.ts, src/common/types/Flyover/index.ts, src/common/types/index.ts, src/common/types/store.ts, src/pegin/components/create/ConfirmTx.vue, src/pegin/components/create/ConfirmationSteps.vue, src/pegin/components/create/PegInForm.vue, src/pegin/components/create/PeginOptionCard.vue, src/pegin/store/FlyoverPegin/mutations.ts, tests/unit/common/PeginQuote.spec.ts
I've defined the PeginQUote class in order to assing all the required
behavior to each specific quote object
=> Refactor: PeginQuote class definition

package-lock.json, package.json
Update flyover version to avoid `getProviders()` error response
=> fix: flyover 1.5.2

src/pegin/components/create/ConfirmationSteps.vue, src/pegin/components/create/PegInForm.vue
Watch address changes, ensure the most recent quote is selected and get address from flyover peg-in store.
Also, fix the incorrect provider address displayed in the confirmation steps for flyover peg-ins when using software wallets.
=> Fix pegin destination address usage

src/pegin/store/FlyoverPegin/actions.ts, src/pegout/store/FlyoverPegout/actions.ts, tests/unit/common/PeginQuote.spec.ts
Ignore register flyover call failures.
Add rejection errors.
Fix line length warning.
=> Remove warnings

src/pegout/components/PegoutOption.vue
[TWPAPP-999](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-999)
=> fix: create consistent spacing between elements on pegout option card

src/common/styles/_utilities.scss, src/pegout/components/PegoutForm.vue, src/pegout/components/PegoutOption.vue
[TWPAPP-1004](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1004)
* Disabled Send button while there is valid no selected option
* Disabled input for native option
* Move recaptcha badge up so it does not cover buttons on the footer
=> fix: disable send button while getting quotes

src/common/router/index.ts, src/common/views/SuccessTx.vue, src/pegin/components/create/SendBitcoin.vue, src/pegout/components/PegoutForm.vue, src/pegout/components/PegoutOption.vue
[TWPAPP-995](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-995)
=> Clean wallet connections

src/common/components/status/StatusProgressBar.vue, src/common/components/status/TxPegin.vue, src/common/components/status/TxPegout.vue, src/common/views/Home.vue, src/status/views/Status.vue
[TWPAPP-996](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-996)
=> refactor: tx not found message on status

src/pegout/components/PegoutForm.vue
[TWPAPP-1029](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1029)
=> fix: show pegout options only with valid amount

.github/workflows/build.yml
- Github will deprecate ubuntu-20.04 then i changed to ubuntu-latest
=> adding ubuntu-latest version

package-lock.json, package.json, src/pegin/components/create/PegInForm.vue, src/pegin/components/create/PeginOptionCard.vue, src/pegout/components/PegoutForm.vue, src/pegout/components/PegoutOption.vue
- alert message when the users amount is not enough to complete flyover transaction even if the balance is lt amount
- advance version to 3.0.0
- added alt text for fees on tx pegin and pegout
- fix links to dev.rootstock.io
=> minor fixes ref v3.0.0

src/App.vue
[TWPAPP-1183](https://rsklabs.atlassian.net/jira/software/projects/TWPAPP/boards/128?selectedIssue=TWPAPP-1183)
It was not possible to remove Xverse from reown's list. Instructions on reown's [documentation](https://docs.reown.com/appkit/svelte/core/options#excludewalletids) does not work.
` '2a87d74ae02e10bdd1f51f7ce6c4e1cc53cd5f2c0b6b5ad0d7b3007d2b13de7b', // Xverse`
=> fix: hide wallets reown
